"use client";

import { useState, useEffect } from "react";
import { createClient } from "./lib/supabase";// Define your interfaces
interface Flashcard {
  front: string;
  back: string;
}

interface User {
  id: string;
  email?: string;
}

export default function Home() {
  // --- State Variables ---
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [saving, setSaving] = useState<boolean>(false);
  const [topic, setTopic] = useState<string>("");
  const [cards, setCards] = useState<Flashcard[]>([]);
  const [currentIndex, setCurrentIndex] = useState<number>(0);
  const [isFlipped, setIsFlipped] = useState<boolean>(false);
  const [deckTitle, setDeckTitle] = useState<string>("My AI Flashcard Deck");

  // --- 1. Auth Listener Hook (Processes URL Token & Changes) ---
  // --- 1. Auth Listener Hook (Processes URL Token & Changes) ---
  useEffect(() => {
    const supabase = createClient();

    // Catch session tokens directly out of the URL hash if present
    supabase.auth.getSession().then(({ data: { session } }: { data: { session: any } }) => {
      if (session) {
        setUser(session.user as User);
      }
    });

    // Explicitly type _event and session to satisfy the compiler
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event: string, session: any) => {
      if (session) {
        setUser(session.user as User);
      } else {
        setUser(null);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  // --- 2. Google OAuth Function ---
  async function loginWithGoogle() {
    const supabase = createClient();
    const { error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        redirectTo: `${window.location.origin}/`,
        queryParams: {
          access_type: 'offline',
          prompt: 'consent',
        },
      },
    });
    if (error) console.error("Login error:", error.message);
  }

  // --- 3. Logout Function ---
  async function handleLogout() {
    const supabase = createClient();
    await supabase.auth.signOut();
    setUser(null);
  }

  // --- 4. Dummy Card Generator (Replace with your actual Groq API call) ---
  async function generateFlashcards() {
    if (!topic.trim()) return alert("Please enter a topic!");
    setLoading(true);
    setCards([]);
    setCurrentIndex(0);
    setIsFlipped(false);

    // Simulated API delay
    setTimeout(() => {
      const mockCards: Flashcard[] = [
        { front: `What is the core concept of ${topic}?`, back: "This is a placeholder answer generated by the app." },
        { front: `Explain a key mechanism behind ${topic}.`, back: "Another sample answer text." },
        { front: `Name a common use-case for ${topic}.`, back: "A standard practical application example." }
      ];
      setCards(mockCards);
      setLoading(false);
    }, 1500);
  }

  // --- 5. Database Save Pipeline ---
  async function saveDeck() {
    if (!user) {
      alert("Please log in to save your decks!");
      return;
    }

    if (!cards || cards.length === 0) {
      alert("Generate some flashcards first before saving!");
      return;
    }

    setSaving(true);
    const supabase = createClient();

    try {
      // 1. Uses the safe title state variable instead of window.prompt()
      const finalizedTitle = deckTitle.trim() || "Untitled AI Deck";

      // 2. Insert the deck parent row
      const { data: deckData, error: deckError } = await supabase
        .from("decks")
        .insert([
          {
            user_id: user.id,
            title: finalizedTitle,
          },
        ])
        .select()
        .single();

      if (deckError) throw deckError;

      // 3. Format the children records matching your table schema
      const cardsToInsert = cards.map((card) => ({
        deck_id: deckData.id,
        front: card.front,
        back: card.back,
      }));

      // 4. Batch insert into the cards table
      const { error: cardsError } = await supabase
        .from("cards")
        .insert(cardsToInsert);

      if (cardsError) throw cardsError;

      alert(`🎉 "${finalizedTitle}" successfully synced to Supabase!`);
    } catch (err: any) {
      console.error(err);
      alert("Database Error: " + err.message);
    } finally {
      setSaving(false);
    }
  }

  // --- Navigation Controls ---
  const handleNext = () => {
    setIsFlipped(false);
    setCurrentIndex((prev) => (prev + 1) % cards.length);
  };

  const handlePrev = () => {
    setIsFlipped(false);
    setCurrentIndex((prev) => (prev - 1 + cards.length) % cards.length);
  };

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100 p-8 font-sans">
      {/* Top Navbar Section */}
      <header className="max-w-4xl mx-auto flex justify-between items-center border-b border-neutral-800 pb-4 mb-12">
        <h1 className="text-xl font-bold tracking-tight bg-gradient-to-r from-purple-400 to-pink-500 bg-clip-text text-transparent">
          AI Flashcard Generator
        </h1>
        <div>
          {user ? (
            <div className="flex items-center gap-4">
              <span className="text-sm text-neutral-400">Logged in as: <strong className="text-neutral-200">{user.email}</strong></span>
              <button onClick={handleLogout} className="text-sm bg-neutral-800 hover:bg-neutral-700 text-neutral-200 px-4 py-1.5 rounded-lg transition">
                Logout
              </button>
            </div>
          ) : (
            <button onClick={loginWithGoogle} className="text-sm bg-white hover:bg-neutral-200 text-black font-semibold px-4 py-1.5 rounded-lg transition flex items-center gap-2">
              Sign In with Google
            </button>
          )}
        </div>
      </header>

      {/* Main Generator Section */}
      <section className="max-w-2xl mx-auto space-y-8">
        <div className="flex flex-col gap-2">
          <label className="text-sm font-medium text-neutral-400">What do you want to learn today?</label>
          <div className="flex gap-2">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g., Docker multi-stage builds, JavaScript closures..."
              className="flex-1 bg-neutral-900 border border-neutral-800 rounded-lg px-4 py-2 text-sm text-white focus:outline-none focus:border-purple-500 transition"
            />
            <button onClick={generateFlashcards} disabled={loading} className="bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white text-sm font-semibold px-6 py-2 rounded-lg transition">
              {loading ? "Generating..." : "Generate"}
            </button>
          </div>
        </div>

        {/* Interactive Flashcard UI */}
        {cards.length > 0 && (
          <div className="space-y-6">
            <div className="flex justify-between items-center text-xs text-neutral-500">
              <span>Card {currentIndex + 1} of {cards.length}</span>
              <span>Click card to flip</span>
            </div>

            <div 
              onClick={() => setIsFlipped(!isFlipped)}
              className="h-64 bg-neutral-900 border border-neutral-800 rounded-xl p-8 flex items-center justify-center text-center cursor-pointer hover:border-neutral-700 transition duration-300 shadow-xl"
            >
              <p className="text-lg font-medium max-w-md">
                {isFlipped ? cards[currentIndex].back : cards[currentIndex].front}
              </p>
            </div>

            {/* Navigation & Storage Actions */}
            <div className="flex justify-between items-center gap-4">
              <button onClick={handlePrev} className="text-sm bg-neutral-900 border border-neutral-800 hover:bg-neutral-800 px-4 py-2 rounded-lg transition">
                ← Prev
              </button>

              {/* Seamless Title Input + Save Action Inline Block */}
              <div className="flex items-center gap-2 border border-neutral-800 bg-neutral-900 p-1.5 rounded-xl">
                <input
                  type="text"
                  value={deckTitle}
                  onChange={(e) => setDeckTitle(e.target.value)}
                  placeholder="Deck name..."
                  className="bg-transparent text-xs text-white px-3 py-1 focus:outline-none max-w-[160px] border-r border-neutral-800"
                />
                <button onClick={saveDeck} disabled={saving} className="bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white text-xs font-bold px-4 py-1.5 rounded-lg transition">
                  {saving ? "Saving..." : "Save Deck"}
                </button>
              </div>

              <button onClick={handleNext} className="text-sm bg-neutral-900 border border-neutral-800 hover:bg-neutral-800 px-4 py-2 rounded-lg transition">
                Next →
              </button>
            </div>
          </div>
        )}
      </section>
    </main>
  );
}